### ISSUE TITLE
May this can load model train by c++ version

### ISSUE THREAD

**Issue by Trangle** [ivanhk/fastText_java#28]
the wrong error information is:
java.lang.IllegalArgumentException: Unknown loss_name enum value :4
	at fasttext.Args$loss_name.fromValue(Args.java:49)
	at fasttext.Args.load(Args.java:127)
	at fasttext.FastText.loadModel(FastText.java:147)

I trained this model use parameter like this:
fastText.exe supervised -input news_for_train1.csv -output news_ft2.model -dim 64 -lr 0.1 -epoch 100 -wordNgrams 5 -loss softmax

**Comment by attapol** [comment]
I've got the same problem.

**Comment by iceduanxx** [comment]
I've got the same problem.

**Comment by sszuev** [comment]
It seems this repo is not supported anymore, you can try our fork https://github.com/sszuev/fastText_java Up-to-date models (currently v12) must be loaded fine
